In [1]:
import mlx.core as mx



In [3]:
mx.random.uniform( )

array(0.276248, dtype=float32)

In [4]:
mx.full(12 , 4 , dtype=mx.int8)

array([4, 4, 4, ..., 4, 4, 4], dtype=int8)

In [5]:
current_player = (mx.random.uniform( ) > 0.5).astype(mx.int8)

In [6]:
mx.where(
        current_player == 0 ,
        mx.array([ 0 , 1 , 2 , 3 , 4 , 5 ] , dtype=mx.int8) ,
        mx.array([ 6 , 7 , 8 , 9 , 10 , 11 ] , dtype=mx.int8) ,
)

array([6, 7, 8, 9, 10, 11], dtype=int8)

In [7]:
 mx.zeros(2 , dtype=mx.int8)

array([0, 0], dtype=int8)